### ISSUE TITLE
zulipbot is not responding to label requests

### ISSUE THREAD

**Issue by synicalsyntax** [zulip/zulipbot#100]
zulipbot's `label` command is not working (see [here](https://github.com/zulip/zulip/issues/4825) for an example).

@zulipbot label "bug"

**Comment by lonerz** [comment]
Also, for some reason, sometimes zulipbot doesn't mention area teams when you add labels when you create an issue (not after).

**Comment by synicalsyntax** [comment]
Closing issue, as labels seem to be working consistently again (maybe zulipbot was temporarily offline?); will reopen if issue reoccurs
