### ISSUE TITLE
Get rid of merge conflict warning when user pushes new mergeable code

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#102]
We should get rid of the merge conflict warning when the user pushes new code that is mergeable. This will help the user know that the merge conflict is not there anymore and will allow future merge conflict warnings to be a new comment, which will mention the author instead of editing a comment, which doesn't mention the author again.

Bonus: Duplicate merge conflict warnings should not be made.

**Comment by synicalsyntax** [comment]
Closed in e4e6299 (duplicate merge conflict warnings had already been prevented in the first place)

Same behavior might be worth implementing for "no issue-referencing commits in a PR" warnings.
