### ISSUE TITLE
Support assigning yourself as a reviewer on a PR

### ISSUE THREAD

**Issue by eeshangarg** [zulip/zulipbot#106]
I think it would be a good feature to have a command that allows a person to assign themselves as a reviewer on a pull request. With so much peer code review going on, its important that its clear who is reviewing a certain PR. :) Something like `@zulipbot review`. Thoughts?

**Comment by lonerz** [comment]
@eeshangarg can you try `@zulipbot claim` on a PR, it should allow you to claim that PR.

**Comment by eeshangarg** [comment]
@lonerz: Just tried that. Doing that assigns you as an 'assignee', not as a reviewer!

**Comment by lonerz** [comment]
@eeshangarg: if you just review the PR, you'll be added as a reviewer. I don't really understand the need to comment `@zulipbot review`.

**Comment by eeshangarg** [comment]
@lonerz: Tim and I were discussing how I can let him know if I am going to review a certain PR (in some cases, I am collaborating with the person who submitted the PR), and he recommended that I submit it as an issue after I couldn't assign myself as a reviewer. Its great for when I know that I can review something before it gets to reviewers who already have a lengthy queue of PRs to review (like Tim). :)

**Comment by lonerz** [comment]
@eeshangarg Great, that makes sense. I think we need to decide between `@zulipbot review` or `@zulipbot reviewer`. The `reviewer` makes it more clear what you are doing I think?

**Comment by eeshangarg** [comment]
@lonerz: Yeah I agree `reviewer` is better. Let's go with that one. :) `review` seemed okay because its a verb like `claim`. But, `reviewer` makes it a bit more explicit that I want to be the reviewer.

**Comment by synicalsyntax** [comment]
Hey @eeshangarg, sorry for getting back to you late. Just wanted to let you know that the way reviews/reviewers work is that you get automatically assigned as a reviewer on a PR if you [submit a review](https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/) on it. Thus, there isn't a way to assign you as a reviewer on a PR without submitting a review on your part.

I think what you should do instead is assign yourself as an assignee to the PR instead. Does that sound good?

**Comment by eeshangarg** [comment]
@synicalsyntax: Ah okay, but as a "collaborator", I can't assign myself to a PR unless it was submitted by me. So what me and Tim  had discussed was, what if I plan on reviewing something tonight and need to let him know that he doesn't need to because I eventually will when I get to a computer? Sort of a way of letting reviewers know that I have a PR in my queue for review? :)

**Comment by lonerz** [comment]
You can use `@zulipbot claim`, like as above. @eeshangarg

**Comment by eeshangarg** [comment]
@lonerz: Cool, sounds good! I guess that's the only option then! Thanks!

**Comment by synicalsyntax** [comment]
@eeshangarg @lonerz Actually, we just deprecated claiming PRs with the `claim` command, but I'll push a quick commit to complete your feature request :)

**Comment by synicalsyntax** [comment]
@eeshangarg Since zulipbot hasn't been synced with master yet, you can still use `@zulipbot claim` to assign yourself to a PR, but make sure to also run `@zulipbot remove "in progress"` to remove the "in progress" label that gets added to the PR.
