### ISSUE TITLE
Check for commit message references is broken

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#114]
https://github.com/zulip/zulip/pull/5807#issuecomment-319262906

(I think this has been broken since the beginning.. however it is probably a nice feature to still have)

**Comment by synicalsyntax** [comment]
Probably a lapse in the API, and this is the only time where this occurrence has happened. Closing issue.

**Comment by lonerz** [comment]
We should probably only be checking the PR description and not all comments.

**Comment by synicalsyntax** [comment]
We don't check comments for commit references?

**Comment by lonerz** [comment]
No, the comments reference an issue and zulipbot tells them to put `Fixes: #1234` in one of the commits.

FYI: there's a merge conflict bug you recently introduced and we're talking about it on chat.zulip.org

**Comment by synicalsyntax** [comment]
Cause pinpointed and determined to no longer relevant (has been fixed in recent commits to master) in the [discussion](https://chat.zulip.org/#narrow/stream/zulipbot/topic/merge.20conflict.20notices). Closing again.
