### ISSUE TITLE
More precise check for "Fixes #1234" being in the wrong place

### ISSUE THREAD

**Issue by timabbott** [zulip/zulipbot#118]
For https://github.com/zulip/python-zulip-api/pull/85#issuecomment-324568735, we're bugging him because he mentioned an issue, but he's not claiming the issue was fixed, and so this isn't something we should be complaining about.  I wonder if we should just check for `fixes #123` in the commit message, not simply e.g. `#123`.

(See https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by lonerz** [comment]
Closed this on accident. Pretty much how this check works is if in a PR comment there's a reference like `#123` it looks in the commit messages to see if there exists a `Fixes #123` in it.

I would think that (1) we should probably see if the comment has "fixes" or any of the keywords before `#123` the reference
