### ISSUE TITLE
Multiple whitespaces between bot name and command are not ignored

### ISSUE THREAD

**Issue by yanokwa** [zulip/zulipbot#123]
Multiple whitespaces between bot name and command are not ignored. This is tricky to detect because Github's UI throws away extra white spaces in comments. You can see this if you are able to edit the post.

**text**
works (one space between bot and claim: `@opendatakit-bot claim`
fails (two spaces between bot and claim): `@opendatakit-bot  claim`

**image**
![space](https://user-images.githubusercontent.com/32369/30559207-c5fddc24-9cab-11e7-8f76-5e7fc81f1d1e.png)

**Comment by lonerz** [comment]
Thanks for the issue report. We've experienced this before and probably should fix it. I think one way we can do this is using a simple `split()` at whitespace and just look at commands from there. @synicalsyntax what do you think?

**Comment by synicalsyntax** [comment]
Will just implement greedy white space regex matching after I finish my bio midterm
