### ISSUE TITLE
Join forces with corobo

### ISSUE THREAD

**Issue by sils** [zulip/zulipbot#124]
hi, we're doing some stuff similar to this with corobo - maybe we should work together on sth?

CC @Meetmangukiya main corobo dev

**Comment by lonerz** [comment]
@sils Hi! Do you all have a code repo that we can look at?

**Comment by sils** [comment]
yeah, sorry https://github.com/coala/corobo

**Comment by lonerz** [comment]
@sils Ah, interesting bot you have there! What are you interested in collaborating on?

**Comment by synicalsyntax** [comment]
Your bot is written in Python, and our is in Node.js, so can you please elaborate on what exactly we could accomplish by merging? Migrating to an entirely different language might be counterproductive.

**Comment by synicalsyntax** [comment]
Additionally, according to your README:

> corobo is a Python based chatbot that could be connected to many messaging platforms including Slack, HipChat, Telegram, IRC, XMPP, Tox, Campfire, Gitter, Skype. Check all the backends available here

> This repository is mainly a collection of plugins that are written for errbot. Errbot is a Python based chatbot framework.

zulipbot's goal isn't to integrate with Errbot, but manage GitHub issues/pull requests for better productivity instead.

Would you be willing to chat with us on the #zulipbot stream on https://chat.zulip.org/? I think communication will be faster this way :)

**Comment by sils** [comment]
I'm not entirely sure, maybe we can build one of our tools to suit both our usecases. I don't see us merging two completley different projects indeed. I don't know about @meetmangukyia, fun is a thing but most extreme case I can see e.g. us abandoning corobo if your tool works just as well for us but maybe it's just exchanging information on what we do and what we've learned while building that. Open source is all about sharing and collaboration right?

**Comment by lonerz** [comment]
Link to conversation: https://chat.zulip.org/#narrow/stream/zulipbot/subject/corobo/near/298578
