### ISSUE TITLE
Investigate implementing Zulipbot as a probot plugin

### ISSUE THREAD

**Issue by patcon** [zulip/zulipbot#126]
Just wanted to put it on your radar:
https://probot.github.io/docs/

Probot is an [as yet unreleased?] project of GitHub that aims to aims to make easy just the sort of automation that Zulipbot does. It doesn't do anything out of the box, but is intended to be modular.

Potential benefits off top-of-head:

- less code to maintain
- taking the blessed path of GitHub (which their developers are working on with you)
- ability to let anyone use your app without self-hosting
- split zulipbot into multiple apps, so people can install each app for features they want. Yay unix philosphy!

Anyhow, love the premise of this project as-is! Just wanted to put this out there in case it's helpful :)

**Comment by patcon** [comment]
Oh, one more:

- allow folks to install zulipbot features thought github UI without messing with config files

**Comment by synicalsyntax** [comment]
> Many of the most popular Probot apps are hosted, so there’s nothing for you to deploy and manage

It looks we'd have to provide hosting support for any apps we put up on probot? Not sure if this is within our interests.

> Some API endpoints are not available on GitHub Apps yet, so check which ones are available first.

This is my main concern with making zulipbot into a GitHub App; we use repository webhooks to respond to GitHub events, and some endpoints (like the "member" event) aren't available to GitHub Apps. So once GitHub expands its API, I'd be interested in reconsidering this prospect.

**Comment by patcon** [comment]
Cool, that makes sense!

fwiw, hosting is on heroku, and so the app wakes up when hit by webhooks. So it would need the 24-hour hobby dyno for $7/month. I assume that tulipbot has activity regularly enough that it would be using the 24 hours anyhow, so it would simply let others use the bot you are using anyhow.

But I mean, if you want to leave room to break zulipbot and not have it be a bit issue outside your org, then it totally makes sense not to share your app in that way. But i could easily imagine using heroku build pipelines to have zulip org use the staging app, and then push to prod when you've used it and know its golden.

Anyhow, I'm only saying all this because it would make it way easier for other projects to use your tech and your tried-and-true workflow :) Hopefully I'm not coming across as pesky!

Hoping you have a chance to revisit when they update their APIs :D
