### ISSUE TITLE
Check commit message should make sure referenced number is an issue

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#129]
Currently, we just check for keywords and then automatically take into account the number as an issue. However, it may not necessarily be an issue, so make sure to check if it is an issue.

Example: https://github.com/zulip/zulip/pull/7333

**Comment by lonerz** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
According to the GitHub UI, zulip/zulip#7333:

![screenshot at nov 08 18-55-13](https://user-images.githubusercontent.com/15116870/32586556-0274a3ca-c4b8-11e7-9317-d51f95531a97.png)

Our goal with the issue reference checks is to mock GitHub's [closing issue keywords](https://help.github.com/articles/closing-issues-using-keywords/) as much as possible, and I'm not sure if we want to deviate from GitHub even though they are mistaken in this case.
