### ISSUE TITLE
Fix failing invitation when claiming second zulip issue in a different zulip repository

### ISSUE THREAD

**Issue by abhigyank** [zulip/zulipbot#149]
It seems if one is already a collaborator on one project and tries `@zulipbot claim` on another repo, invitations are not sent to the account for collaborating for that repo.
[Discussion here](https://chat.zulip.org/#narrow/stream/general/topic/Github.20Invititations)

**Comment by amanagr** [comment]
Relevant Chats :
 - https://chat.zulip.org/#narrow/stream/general/subject/Github.20Invititations/near/493675  
 - https://chat.zulip.org/#narrow/stream/issues/subject/.238054/near/478886

Reproducing the error:
 - The user claims and accepts his first issue in zulip/X repo.
 - User claims his 2nd issue in zulip/Y repo.

Problems:
 - User doesn't receive the invitation send time. 
 - Gets this error: **Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or you are not logged into the invited account.**
 - User should not get the invitation when he claims an issue for the second time. He should be directly assigned.
