### ISSUE TITLE
Buggy notices about `****` teams

### ISSUE THREAD

**Issue by timabbott** [zulip/zulipbot#152]
https://github.com/zulip/zulip/pull/8638#issuecomment-371832378

I think this might be the size labels?

**Comment by VibhorCodecianGupta** [comment]
Hello sir, what exactly seems to be the problem here?

**Comment by timabbott** [comment]
@VibhorCodecianGupta zulipbot shouldn't be sending notices with the empty string as the team name; it's a clear bug.

**Comment by synicalsyntax** [comment]
I haven't seen a team error since the comment in #8638, which coincidentally one of the last PRs opened before the most recent zulipbot deploy (with commit 09281c89, which should've fixed this issue). I will tentatively close this, but feel free to reopen if you notice more errors.
