### ISSUE TITLE
Avoid false warnings for "have not referenced that issue in your commmit message".

### ISSUE THREAD

**Issue by showell** [zulip/zulipbot#155]
See https://github.com/zulip/zulip/pull/9091 for context.

@timabbott merged my first three commits there (probably from his laptop) and closed the relevant issue that I mention in the description.  But he left two commits to merge later (for context, it was right before a release, but as you know, he'll often merge just the first couple commits).

Later zulipbot gave me a warning that I haven't updated my commit messages with the relevant issues.

**Comment by synicalsyntax** [comment]
Looks like you still reference the issue in the pull request description but the debased commits don't mention th  issue. I think we can solve this by warning only if the issue is still open.
