### ISSUE TITLE
Mention corresponding area label teams when area labels are added to issues

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#17]
When an `area` label is added to an issue, the corresponding team should be mentioned and notified by zulipbot

**Comment by lonerz** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
Referencing https://github.com/zulip/zulip/issues/3703here, the original request for this feature.

**Comment by lonerz** [comment]
@zulipbot claim

**Comment by lonerz** [comment]
@zulipbot abandon

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
Added in 33eae4e
