### ISSUE TITLE
Create website for zulipbot

### ISSUE THREAD

**Issue by synicalsyntax** [zulip/zulipbot#18]
Fun fact: zulipbot is deployed on the https://zulip.org/zulipbot/ page. 

When you visit it, you get redirected to this repository (relevant lines 18-20 in `src/index.js`). It'd be nice to set up a website to introduce zulipbot and its features as well as link back to this repository, which would make contributions to zulipbot more welcoming, I think.

Thoughts?

**Comment by synicalsyntax** [comment]
@zulipbot label "feedback wanted" "bug"

**Comment by synicalsyntax** [comment]
@zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
@zulipbot remove "test"

**Comment by lonerz** [comment]
@synicalsyntax we can write up a Zulip doc with zulipbot. That's the first thing that comes to mind.

**Comment by synicalsyntax** [comment]
@zulipbot remove "question"

**Comment by synicalsyntax** [comment]
@zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
@zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
Yes, https://github.com/zulip/zulip/issues/3771 is open for that issue; I think I'll focus on that first before getting a website up, thanks.

**Comment by lonerz** [comment]
@synicalsyntax we can close this now.
