### ISSUE TITLE
Support default branch names other than master

### ISSUE THREAD

**Issue by andersk** [zulip/zulipbot#189]
GitHub is [changing](https://github.com/github/renaming) the default branch name from `master` to `main`, and we intend to update our repositories as such. To enable this, we’ll need to fix the hard-coded references to `master` in zulipbot, most importantly this one:

https://github.com/zulip/zulipbot/blob/39b257ee804f2216763e6320a4a21ff09816d914/src/events/push.js#L3

**Comment by synicalsyntax** [comment]
Agreed, will get to work on it ASAP :)
