### ISSUE TITLE
Adding area label support to pull requests

### ISSUE THREAD

**Issue by synicalsyntax** [zulip/zulipbot#23]
Mention the corresponding area label team and label PR with area label when PR mentions another issue.

- [ ] Check body for newly created pull request
- [x] Check body for pull request (issue) comment
- [x] Check body for pull request review
- [x] Check body for pull request review comment

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by lonerz** [comment]
@synicalsyntax I can work on newly created PRs. However, feel free to continue if you already started.

**Comment by synicalsyntax** [comment]
I haven't started on newly created PRs, feel free to go ahead

**Comment by synicalsyntax** [comment]
@lonerz Since I had the framework already set up, I went ahead and added support for newly created PRs, sorry if you already started working on it
