### ISSUE TITLE
Get rid of duplicate code

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#27]
We should get rid of duplicate things and create functions for them, especially the following:
- [x] create comment function
- [x] authentication (??)
- [x] getting issue labels

For the future:
- [ ] getting labels in a repo
- [ ] remove label function (we can actually just use replace label function)
- [ ] add label function

Feedback would be nice and any other suggestions for duplicate functions. The one that should be taken care of is a comment function.

**Comment by lonerz** [comment]
@zulipbot label "feedback wanted", @zulipbot claim

**Comment by lonerz** [comment]
Not sure if we can actually write functions for removing/adding labels, since we need to access the responses...

**Comment by synicalsyntax** [comment]
Authentication would definitely be great. We're looking for responses a lot of the time we use a label function, but we can probably have the function return the associated labels if necessary.

**Comment by lonerz** [comment]
Sure, it'll probably work out.

**Comment by lonerz** [comment]
@synicalsyntax working on authentication right now.

**Comment by synicalsyntax** [comment]
@lonerz Eliminated the `getIssueLabels` function altogether in a5e1f7c and b13e0ed, since we can just get the issue labels from the responses and payloads themselves :)

**Comment by lonerz** [comment]
@synicalsyntax those require `.then()` which means that we'll have to look into async functions...

**Comment by lonerz** [comment]
@synicalsyntax I went through all the code and I think we got rid of all the duplicate functions. Closing for now.
