### ISSUE TITLE
Mention corresponding area label teams when issue is abandoned completely

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#37]
When someone or some people claim(s) a task at first and when everyone abandons the task, the corresponding area label team should be mentioned of the open issue with no assignees.

**Comment by lonerz** [comment]
@timabbott feedback on this?

**Comment by timabbott** [comment]
Hmm, I think given that on a large project like zulip/zulip, like 80-90% of issues are unclaimed, I'm not sure we need a special notification for this state (especially since the area label team should be subscribed already from when the issue was opened/labeled in the first place, and thus should be receiving notifications, unless I'm mistaken...).

**Comment by lonerz** [comment]
@zulip/gci test

**Comment by lonerz** [comment]
Hmmm, why would the area label team be automatically subscribed? @timabbott They are only mentioned by zulipbot, but that shouldn't automatically subscribe them to the issue.

**Comment by lonerz** [comment]
What I was thinking was if the issues was claimed by a person, but that person decided that it was too hard or didn't want to do it and abandoned it. Then zulipbot will mention the area label team and say that the PR is up for grabs again.

**Comment by synicalsyntax** [comment]
If you are mentioned in a specific issue (aka mentioning of the label team by zulipbot), you'd be automatically subscribed to notifications for the issue/PR.

**Comment by lonerz** [comment]
@synicalsyntax really hmm, then I'll close this issue.

**Comment by timabbott** [comment]
Have we definitely confirmed that GitHub behaves that way?

**Comment by synicalsyntax** [comment]
Yep, GitHub subscribes anyone, team or member regardless, to an issue/PR by mention. https://help.github.com/articles/about-notifications/

**Comment by timabbott** [comment]
Great!  @lonerz comment got me worried a bit that I was confused about how this works :)
