### ISSUE TITLE
Add linter(s) to Travis-CI

### ISSUE THREAD

**Issue by refeed** [zulip/zulipbot#38]
It always a good idea to set up a linter for code readability and quality, since this repository doesn't has a linter yet, so I'd recommend to set up it.

I'd recommend `eslint` for this repo, since it supports ES6 and works with some framework like CommonJS, and easy to configure. Any thoughts for this? like rules for the linter, or recommend another linter.

**Comment by refeed** [comment]
@zulipbot label "feedback wanted"

@zulipbot claim

**Comment by lonerz** [comment]
@refeed I thought there's already a eslint linter that comes with gulp. I've been using for the past week or so.

**Comment by synicalsyntax** [comment]
Yeah, I've already set up Eslint for listing with Gulp that's used in Travis CI. Try running `gulp static` to run it. Unit tests/coverage are something we need to work on, though.

**Comment by refeed** [comment]
Oh ok, I didn't saw it before this..
