### ISSUE TITLE
Remove assignee and "in progress" label for inactive claimed issues

### ISSUE THREAD

**Issue by synicalsyntax** [zulip/zulipbot#42]
For claimed/in progress issues that have been inactive (no comments, no pull requests referenced, etc.) for a week, @zulipbot should ask the assignee whether they are still working on it. 

If the assignee doesn't respond with "Yes I'm still working on it" or something similar within a time limit of the prompt, zulipbot remove the assignee and in progress label from the issue to allow other people to work on it.

**Comment by lonerz** [comment]
@synicalsyntax would the comments/PR referenced be from the assignee?

**Comment by synicalsyntax** [comment]
Yes

**Comment by synicalsyntax** [comment]
@zulipbot claim
