### ISSUE TITLE
Check title of PRs for "WIP" before mentioning corresponding area label teams

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#46]
Pull requests that contain "[WIP]" in their titles should not reference area label teams until the "[WIP]" status is removed from the title.

(Description added by @synicalsyntax)

**Comment by lonerz** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot label "enhancement"

**Comment by lonerz** [comment]
@zulipbot label "enhancement"

**Comment by synicalsyntax** [comment]
@lonerz Were you trying to claim this, or were you trying to test if zulipbot was working?

**Comment by lonerz** [comment]
@synicalsyntax no, I was just testing if zulipbot was working.
