### ISSUE TITLE
Tracking inactive claimed issues should take open referenced PRs into account

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#49]
Currently, issues that have been inactive in the comments for 7 days but have an open PR referenced are being flagged as inactive. This shouldn't happen.

**Comment by lonerz** [comment]
You may want to use a map of open PRs and open issues and cross-check them.

**Comment by lonerz** [comment]
@synicalsyntax can you pick this up? I'm pretty busy, so if you want to, this issue is open.

**Comment by lonerz** [comment]
@synicalsyntax why did zulipbot still give a warning [#3992](https://github.com/zulip/zulip/issues/3992)?

**Comment by synicalsyntax** [comment]
@lonerz The PR body didn't reference the issue
