### ISSUE TITLE
Post at most one area message per area per conversation. 

### ISSUE THREAD

**Issue by rishig** [zulip/zulipbot#50]
If you write a comment on a PR that references an issue in area X, zulipbot adds a message to the PR saying "hey folks in area X, check it out", which is great. 
If you add another comment that references a different issue in area X, it would be great if zulipbot did not add another "hey folks in area X, check it out" message. 
https://github.com/zulip/zulip/pull/3946 is an example of where this happened.

**Comment by lonerz** [comment]
@rishig Ah, so no duplicate comments pretty much.

**Comment by rishig** [comment]
ah yeah, a more succinct way to say it :).

**Comment by lonerz** [comment]
Cool, it should just be a simple search through the comments and seeing which area teams have already been mentioned.

**Comment by lonerz** [comment]
@zulipbot claim
