### ISSUE TITLE
Standardize zulipbot name

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#52]
I think we agreed to use "zulipbot" all lowercase instead of "Zulipbot". We should probably change all the spellings to match "zulipbot" now.

**Comment by lonerz** [comment]
@zuliipbot label "help wanted"

**Comment by lonerz** [comment]
@zulipbot label "help wanted"

**Comment by synicalsyntax** [comment]
I've never seen any instances of "Zulipbot" in the docs/files (I've always used "zulipbot"), are there any that you've noticed?

**Comment by lonerz** [comment]
@synicalsyntax maybe I'm wrong. I'll double check right now. Yep, seems like there is nothing with "Zulipbot". Closing this issue.
