### ISSUE TITLE
Inactivity is not checked for older issues

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#58]
I have a feeling that we aren't iterating over all the pages of issues, thus, missing old issues like [#3945](https://github.com/zulip/zulip/issues/3945), which should be labeled inactive.

**Comment by lonerz** [comment]
Actually, I think I might be wrong. This just happened to be an issue with zulipbot itself.

**Comment by synicalsyntax** [comment]
The user probably tried using `@zulipbot claim` when the bot was down, since the issue was never claimed in the first place.

**Comment by synicalsyntax** [comment]
@zulipbot abandon (the thing works, looks like Tim hasn't deployed yet)
