### ISSUE TITLE
Expand issue referencing support.

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#60]
zulipbot should check issue references in:

- [ ] [pull request commit descriptions](https://github.com/zulip/zulip/pull/4041)
- ~~edited pull request descriptions (should make sure it wasn't there first)~~
- ~~edited issue comments (should make sure it wasn't there first)~~

**Note:** GH API does not work consistently for Edit events, see conversation below

(title and description edited by @synicalsyntax)

**Comment by lonerz** [comment]
@zulipbot label "enhancement"

**Comment by synicalsyntax** [comment]
I thought our commit standards discouraged issue references in the title and commit message titles?

**Comment by lonerz** [comment]
With this, then when someone merges your commit, it automatically closes the corresponding issue.

**Comment by synicalsyntax** [comment]
Oh, I thought you meant commit message reference as in:
```
Commit: Fix bug #1234
```

Generally people already reference the issue the PR fixes in the PR description, but I guess we can add it for commit checking too. I guess this is also related to #51, since we need to add support for commit message descriptions for both issues.

We should also probably add support for edited issue comments/PR descriptions, now that I think about it.

**Comment by lonerz** [comment]
Yep.

**Comment by synicalsyntax** [comment]
Did some work on adding command support for "edited" event payloads; unfortunately, the GitHub API is **very** inconsistent with showing the content of the edited body. Specifically, sometimes the content of the edited body is shown as the previous unedited version. I've contacted GitHub about this issue, but until then we might want to hold off on adding support for edits.

**Comment by lonerz** [comment]
Great. GH API is just not as well done as it should be.

**Comment by synicalsyntax** [comment]
Received this reply from GH support:

```
Thanks for reaching out -- that's indeed a problem on our end. The team is investigating the problem and considering possible options, but the problem doesn't seem to be trivial so resolving it will take some time. 

I wish I had better news for you, but I don't. I'll add a note to our internal tracking issue for this so that we can followup with you when there's any news.
```

Looks like it's best to discontinue work on edited comments/bodies until GH API starts working consistently. :(

Also, have there been any cases where "WIP" was removed from a PR title and the label team wasn't pinged afterwards? Pretty sure this edit event issue affects that feature too.

**Comment by lonerz** [comment]
@synicalsyntax we can comment it out for right now.
