### ISSUE TITLE
Make zulipbot check to see if PR commit messages conform with commit messages guideline

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#62]
This can be pretty simple. Check capitalization after a colon, or make sure commit message starts with a colon. Related to #51 (this is a meta-issue).

The guidelines can be found [here](http://zulip.readthedocs.io/en/latest/version-control.html#commit-messages).

**Comment by lonerz** [comment]
@zulipbot label "new feature"

**Comment by synicalsyntax** [comment]
I think they're already trying to implement something similar in zulip/zulip#1131 (looks like they're using gitlint), pinging @timabbott to see if he thinks zulipbot would be a more effective solution than gitlint.

**Comment by lonerz** [comment]
Oh hmm, I thought I've seen this before. Thanks for mentioning.

**Comment by tommyip** [comment]
I think we are trying to run the commit message lint during the testing stage (as part of the Travis test suite), though using Zulipbot for this is an interesting idea.

**Comment by timabbott** [comment]
Let's get it working as part of the test suite, but I can imagine porting it over if we think the user experience would be better to have zulipbot notifying.  I worry a bit that it'd be somewhat spammy when debugging something with bad commit messages, though.

**Comment by lonerz** [comment]
Closing now that git linter has been added.
