### ISSUE TITLE
zulipbot commands after code block text with zulipbot command don't work

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#76]
For example, `@zulipbot  claim`.

The following command will not work when it should.
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
That's because our code looks for the first instance of a `@zulipbot` command and rejects it if it's within a code block.

I guess we could reenable supporting multiple commands in a comment/body?

**Comment by lonerz** [comment]
I feel like we shouldn't take the first instance of `@zulipbot` command from the code block, but the first instance of `@zulipbot` that isn't in codeblocks.

**Comment by synicalsyntax** [comment]
Our regex matches the first instance, and JavaScript doesn't support look-behinds in regex. We'd probably have to reimplement supporting multiple commands (global regex) to enable this.
