### ISSUE TITLE
Commands which are processed is nonintuitive

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#80]
When you have something like below:

@zulipbot label "invalid"
@zulipbot label "enhancement"
@zulipbot label "bug"

It labels "bug" first, which is super unintuitive. We should fix this.

**Comment by synicalsyntax** [comment]
It goes by the alphabetical order in the repository labels.

**Comment by lonerz** [comment]
Hmm, shouldn't it just take the first command and run it?

**Comment by synicalsyntax** [comment]
No, because when we check for labeling, we first process all the repository labels into `repoLabel`, and repository labels are alphabetically by default.
