### ISSUE TITLE
Avoid automatic subscription when claiming an issue for the first time

### ISSUE THREAD

**Issue by YagoGG** [zulip/zulipbot#9]
# Description

If you claim an issue with `@zulipbot claim` for the first time, you are automatically subscribed to the repo (i.e. you start watching it). Therefore, you receive email notifications for everything that happens in the repo, which is a bit annoying, and might be slightly intimidating for new contributors.

# Additional information

The hypothesis here is that being added as a contributor implies becoming a watcher for that repo.

A temporary workaround for this could be adding a message with a link to remove the subscription (e.g. https://github.com/zulip/zulip/subscription), but it'd be great if we could directly avoid this. Maybe it can be done when calling GitHub's API?

**Comment by lonerz** [comment]
@YagoGG there should be a function in the node-github api to deal with this problem: http://mikedeboer.github.io/node-github/

**Comment by YagoGG** [comment]
I wonder if those have to be run as the (un)subscribed user, rather than as the bot.

It's probably specified in those docs, so I apologize in advance (I just made a quick skim).

I would be happy to work on this after I finish with my current PRs, but if anyone else is willing to fix this, feel free to take over :)

**Comment by lonerz** [comment]
@YagoGG I'm almost certain that when you are added as a collaborator, then you are automatically subscribed.

**Comment by YagoGG** [comment]
@lonerz Yup, that's the theory.

However, I wonder if there's anything we can do to avoid it, or at least undo it. If it's completely impossible, I guess that a friendly message pointing to the notification settings (`https://github.com/zulip/<repo>/subscription`) would do the trick.

**Comment by synicalsyntax** [comment]
@YagoGG Unfortunately, I don't think zulipbot can remove your automatic subscription to a repository when you're added as a collaborator; the GitHub API only allows you to modify the notifications of the user you are authenticated as.

**Comment by timabbott** [comment]
I think a good approach is to just add a special comment when we add them to the repo (it's only 1 time per user, so not too spammy), letting them know that they've been subscribed and they may want to edit their notification settings for the repo to just include issues they're following, and not the full firehose.

**Comment by synicalsyntax** [comment]
Sounds good! Will add that in my next push.

**Comment by synicalsyntax** [comment]
@YagoGG Oh, turns out you're not automatically subscribed to a repository's events when you're given push settings.

If you have the **Automatically watch repositories** option selected in https://github.com/settings/notifications, you'll automatically watch a repository when you are given push access to it, but you won't get notifications or watch the repo if you disable that setting. I've tested this out personally and confirmed that this issue doesn't apply to everyone.

@timabbott @lonerz Do you still think that a warning comment should be added even though this isn't an issue for everyone?

**Comment by YagoGG** [comment]
Hmmm, interesting. Nice catch, @synicalsyntax!

I don't remember having modified those settings. Could you guys check whether you have that setting activated by default or not?

**Comment by synicalsyntax** [comment]
That settings is activated by default.

**Comment by lonerz** [comment]
Yep, it is most definitely default.
