### ISSUE TITLE
Unnecessary issue reference warnings on PRs being made

### ISSUE THREAD

**Issue by synicalsyntax** [zulip/zulipbot#97]
zulipbot is leaving unnecessary issue reference warning on pull requests. It should only leave issue reference warnings when an issue is referenced in the body of a pull request (maybe pull request comment too), not any pull request review comments.

See [here](https://github.com/zulip/zulip-mobile/pull/466#issuecomment-300020371) for an example of an unnecessary reference warning.

**Comment by lonerz** [comment]
Hmm, yea. It seems to be doing the opposite of what it is supposed to do.

**Comment by synicalsyntax** [comment]
Closed in 4896868.
