### ISSUE TITLE
Augment the list of the PR reviewers to be notified with the list of potential reviewers taken from data from git-blame / git logs

### ISSUE THREAD

**Issue by rht** [zulip/zulipbot#99]
The current request for CR still relies on having an issue(s) being referenced manually in the PR.
In most cases, the previous committer of the lines as stated by git-blame should be able to give the most relevant feedback. This is the method used by https://github.com/facebook/mention-bot (a patent was filed!) with some more additional tweaks. I know nixpkgs has been using this, due to it being a large-scale high-traffic project.

WDYT of having both of them at the same time, while collecting data over a period of several months (one summer should be sufficient), to test the accuracy (determined by the ratio of folks being mentioned and folks doing the CR) or correlation between the two methods? I'd expect the manual tagging done by a human to be more accurate than an algorithm. But data could tell otherwise.

**Comment by synicalsyntax** [comment]
So from what I can see, mention-bot works by analyzing the following criteria:

> If a line was deleted or modified, the person that last touched that line is likely going to care about this pull request.
> If a person last touched many lines in the file where the change was made, they will want to be notified.

I do think these are two good ways to identify whether someone would be interested in reviewing a PR, but I'm a bit hesitant on collecting data on PRs over a long period of time.

@timabbott, what do you think about this feature proposal?

**Comment by timabbott** [comment]
I'm not sure we need to collect data over time; the info is all there in the commit history.  

I'm a little skeptical that there will be a lot of benefit to this over the existing area teams model that we have; it seems like it could be somewhat spammy in our context where more contributors are volunteers (vs. Facebook's, where most are employees).  

Certainly I'd prioritize this below work on improving the quality of existing features (e.g. being able to turn back on the inactive notices or preventing the merge-conflict warnings from happening when a PR is merged with small changes to the commits but isn't closed for 3 minutes after the merge).
